name: Build, Test, Coverage, Docker and Fly Deploy
on:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version-file: .tool-versions
          cache: true

      - name: Install locked dependencies
        run: deno ci

      - name: Verify
        run: deno task verify

      - name: Coverage
        run: deno task test:coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: coverage.lcov

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          push: false

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only
