name: PR Tests 
on: [pull_request]
jobs:
  build:
    name: Build, lint, test and release on Deno 1.38.5 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Deno v1.38.5
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.38.5

      - name: Cache dependencies 
        run: deno cache deno.json

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-none

      - name: Coverage 
        uses: codecov/codecov-action@v3

      - name: Docker Build
        uses: docker/build-push-action@v4
        with:
          push: false 